test_name: LabJackTest
sampling_frequency: 5Hz
output: 
  CSV: {}
  Chronos: {}
metadata: This is a test for LabJack T7 device using multiple channels.

hardware:
  - name: LabJack
    IP: 172.18.120.132
    Voltage_range: "10V"  # Configuring all channels with a 10V range
    Channels:
      Channel 0:
        name: Voltage_1
        type: differential
        negative_channel: 1
        RMS: true
      Channel 2:
        name: Voltage_2
        type: single-ended
        RMS: false
      Channel 3:
        name: Voltage_3
        type: single-ended
        RMS: true
